const CART_ACTIONS = Object.freeze({
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  UPDATE_ATTRIBUTES: "UPDATE_ATTRIBUTES",
});

export default CART_ACTIONS;
